kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# O "control-plane" é o "master", ou seja, quem gerenciará o Kubernetes.

nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker